# =============================================================================
# deploy_api.ps1
# MSDeploy sync script for .NET API deployment to IIS
#
# This script is generated by the Bitbucket pipeline and uploaded to the
# server before execution. Variables are injected via sed before upload.
#
# Downtime: ~10-30 seconds while app pool is stopped and restarted.
# This is required to release .dll file locks held by the running process.
#
# Protected files (never overwritten):
#   - web.config
#   - appsettings.json
#   - appsettings.*.json  (e.g. appsettings.Production.json)
# =============================================================================

$ErrorActionPreference = 'Stop'

$msdeploy = 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
$source   = 'C:\temp\edge_publish_api'
$dest     = 'IIS_API_PHYSICAL_PATH_PLACEHOLDER'   # injected by pipeline via sed
$appPool  = 'IIS_APP_POOL_NAME_PLACEHOLDER'        # injected by pipeline via sed

Write-Host ">>> Cleaning old extract..."
if (Test-Path $source) { Remove-Item $source -Recurse -Force }

Write-Host ">>> Extracting zip..."
Expand-Archive -Path 'C:\temp\edge_publish_api.zip' -DestinationPath $source -Force

Write-Host ">>> Files extracted:"
Get-ChildItem $source | Select-Object Name

Write-Host ">>> Stopping app pool: $appPool"
Import-Module WebAdministration
Stop-WebAppPool -Name $appPool
Start-Sleep -Seconds 5   # wait for in-flight requests to complete

Write-Host ">>> Running MSDeploy sync..."
# -useCheckSum        : only writes files whose checksum has changed (differential sync)
# -enableRule:DoNotDeleteRule : never deletes files on server not present in source
# -skip rules         : additional protection for config files
& $msdeploy `
  -verb:sync `
  -source:contentPath=$source `
  -dest:contentPath=$dest `
  -skip:objectName=filePath,absolutePath='.*appsettings.*\.json$' `
  -skip:objectName=filePath,absolutePath='.*web\.config$' `
  -useCheckSum `
  -enableRule:DoNotDeleteRule `
  -verbose

Write-Host ">>> Starting app pool: $appPool"
Start-WebAppPool -Name $appPool
Start-Sleep -Seconds 3

Write-Host ">>> Verifying app pool state..."
$state = (Get-WebAppPoolState -Name $appPool).Value
Write-Host ">>> App pool state: $state"
if ($state -ne 'Started') {
  throw "App pool failed to start! State: $state. Check Event Viewer for errors."
}

Write-Host ">>> Cleaning up temp files..."
Remove-Item 'C:\temp\edge_publish_api.zip' -Force -ErrorAction SilentlyContinue
Remove-Item $source -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item 'C:\temp\deploy_api.ps1' -Force -ErrorAction SilentlyContinue

Write-Host ">>> API Deployment complete!"
