# =============================================================================
# deploy_ui.ps1
# MSDeploy sync script for Angular UI deployment to IIS
#
# This script is generated by the Bitbucket pipeline and uploaded to the
# server before execution. Variables are injected via sed before upload.
#
# Protected files (never overwritten):
#   - web.config
#   - assets/configuration/appsetting.json
# =============================================================================

$ErrorActionPreference = 'Stop'

$msdeploy = 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
$source   = 'C:\temp\edge_publish_ui'
$dest     = 'IIS_UI_PHYSICAL_PATH_PLACEHOLDER'   # injected by pipeline via sed

Write-Host ">>> Cleaning old extract..."
if (Test-Path $source) { Remove-Item $source -Recurse -Force }

Write-Host ">>> Extracting zip..."
Expand-Archive -Path 'C:\temp\edge_publish_ui.zip' -DestinationPath $source -Force

Write-Host ">>> Files extracted:"
Get-ChildItem $source | Select-Object Name

Write-Host ">>> Running MSDeploy sync..."
# -useCheckSum        : only writes files whose checksum has changed (differential sync)
# -enableRule:DoNotDeleteRule : never deletes files that exist on server but not in source
#                               (protects assets folder, web.config etc.)
# -skip rules         : additional protection for specific files
& $msdeploy `
  -verb:sync `
  -source:contentPath=$source `
  -dest:contentPath=$dest `
  -skip:objectName=filePath,absolutePath='.*web\.config$' `
  -skip:objectName=filePath,absolutePath='.*appsetting\.json$' `
  -useCheckSum `
  -enableRule:DoNotDeleteRule `
  -verbose

Write-Host ">>> Cleaning up temp files..."
Remove-Item 'C:\temp\edge_publish_ui.zip' -Force -ErrorAction SilentlyContinue
Remove-Item $source -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item 'C:\temp\deploy_ui.ps1' -Force -ErrorAction SilentlyContinue

Write-Host ">>> UI Deployment complete!"
